test(xychart): add missing data tests
airbnb/visx pull request #900
Opened 2020-10-28 18:28 UTC by williaster

#### :house: Internal

This PR adds tests for missing data additions in #898 

@kristw

2020-11-03 14:21 UTC, hshoff requested changes

2020-11-03 14:21 UTC, hshoff commented on packages/visx-xychart/src/components/series/private/BaseBarGroup.tsx
> +  console.log(bars);
👀

2020-11-03 20:00 UTC, williaster commented on packages/visx-xychart/src/components/series/private/BaseBarGroup.tsx
> +  console.log(bars);
🤦 thanks for the catch

2020-11-05 01:28 UTC, hshoff approved these changes

2020-11-05 18:52 UTC, merged